name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  highlight:
    name: Highlight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint gcc gettext git groff make pkg-config texinfo libncurses5-dev

      - name: Clone and configure GNU nano
        run: |
          git clone --depth 1 git://git.savannah.gnu.org/nano.git
          cd nano
          ./autogen.sh
          ./configure --prefix=/usr
          cd -

      - name: Build and install nano
        run: |
          cd nano
          make -j
          sudo make install
          cd -
          nano --version

      - name: Test highlighting files
        run: |
          mkdir -p ~/.nano/
          cp -f ./*.nanorc ~/.nano/
          cp nanorc ~/.nanorc
          echo "" | TERM=xterm timeout 1s nano --rcfile ~/.nanorc >/dev/null 2>error.txt || true
          if grep -v -e "Received SIGHUP or SIGTERM" -e "Too many errors from stdin" -e "Standard input is not a terminal" error.txt; then
            exit 1
          fi
          echo "All seems good!"
